export enum NotificationType {
    
    SUPPORT_REQUEST = 'SUPPORT_REQUEST',
    SUPPORT_REQUEST_MESSAGE = 'SUPPORT_REQUEST_MESSAGE',
    NEW_USER = 'NEW_USER',
    NEW_BID = 'NEW_BID',
    ADD_ON_SUBSCRIBTION = 'ADD_ON_SUBSCRIBTION',
    SUPPLIES = 'SUPPLIES',
    CATALOGUE = 'CATALOGUE',
    NEWS_FEED = 'NEWS_FEED',
    APPOINTMENT = 'APPOINTMENT',
    SUPPLIES_ENQUIRY = 'SUPPLIES_ENQUIRY',
    SUPPLIES_ACCOUNT = 'SUPPLIES_ACCOUNT',
    SECOND_HAND_SUPPLIES = 'SECOND_HAND_SUPPLIES',
    SUPPLY_ORDER = 'SUPPLY_ORDER',
    SECOND_HAND_SUPPLIES_ORDER = 'SECOND_HAND_SUPPLIES_ORDER',
    GENERAL = 'GENERAL',
    
}